### ISSUE TITLE
Edit Run Modal

### ISSUE THREAD

**Issue by Dimwiddle** [sam-kakengi/trackrunner#19]
1.  Clicking on the Most recent run or Personal Best tile opens the modal for editing the Run object.
2.  Data retrieved from `api/run/<id>`
3.  Edit Modal Design [here](https://www.figma.com/design/QeuZ0v64aPp5Hd7SjU8QO1/TrackRunner?node-id=7744-4856&node-type=frame&t=7cYVbKpATB5qcPdp-0)

**Comment by sam-kakengi** [comment]
Finished, updated pull request with changes.
