### ISSUE TITLE
TrackRunner Running Man Icon Size

### ISSUE THREAD

**Issue by Dimwiddle** [sam-kakengi/trackrunner#25]
The running man is not scaled relative to the logo size. It's appearing smaller than the logo text.

Applies to desktop viewport dimensions

![Image](https://github.com/user-attachments/assets/dabb1fe5-b3de-4622-bd41-8bc9b7485661)

**Comment by sam-kakengi** [comment]
Fixed, included with Edit Run Modal pull request.
