### ISSUE TITLE
Log Run Modal - design mismatch

### ISSUE THREAD

**Issue by Dimwiddle** [sam-kakengi/trackrunner#34]
There are some issues with the current Log Run modal and doesn't match the [Figma design](https://www.figma.com/design/QeuZ0v64aPp5Hd7SjU8QO1/TrackRunner?node-id=7640-20404&node-type=frame&t=IUbE5wQ5yj63y3eM-0)

**Expected Form**

- [x] Text for dropdown on Routes field. Colour = white
- [x] The **Start** and **Finish** fields should be removed.
- [x] Add a field **Run Time** in format HH:MM:SS (no time picker, just input directly for that format). This will be converted by the React app in to seconds before sending in the API request.
- [x] Required fields: _Run Time_, _Date_, _Route_ 
- [x] Toast is shown when run is successfully added.

The request being sent by React app should be:

```
{
    "start":  "<Y-m-d>T10:00:00",
    "finished": "<Y-m-d>T11:00:00",
    "duration": <int>,
    "route": <int>,
    "notes": <str>
}
```

**Current Form**

![Image](https://github.com/user-attachments/assets/9df18f4f-c98b-4395-a3aa-809348544dee)

**Comment by sam-kakengi** [comment]
Oh crap, sorry just adding the toast now!
